const en = {
  inspectionAttest: "I confirm that we opened and checked the parcel together, its contents match the declaration, and we sealed it with no unresolved safety concerns.",
  savedRequest: "Your parcel is saved. Retry the request, or manage it in your dashboard.",
  upcoming: "Upcoming travellers", upcomingNote: "See who is travelling and when. No date needed to browse.", viewAll: "View all travellers", viewTrip: "View trip",
  later: "Travellers departing after your selected date", laterNote: "These departures are outside your selected timeframe. Confirm arrival and handover before requesting.", seeLater: "See later departures", anyDate: "Showing all upcoming dates on this route.", noUpcoming: "No upcoming trips yet. Post your parcel so travellers can find you.",
  title: "Contents declaration", private: "Your item list, values and photos are private to you and travellers matched with this parcel. Support can review them when needed.",
  item: "Item description", quantity: "Quantity", value: "Value of this line (USD)", addItem: "Add another item", remove: "Remove", total: "Total contents value", valueNote: "The value of the goods, separate from the fee you pay the traveller.",
  photos: "Photos of the open contents (optional)", handoverPhotos: "Handover photos (optional)", photoNote: "Photos are optional. Add up to 6 JPG, PNG or WebP photos, up to 8 MB each. Keep identity documents and contact details out of photos.", addPhotos: "Add photos", uploading: "Uploading photos…", photoError: "Use JPG, PNG or WebP photos under 8 MB (maximum 6).", photoLoadError: "Photo unavailable. Please refresh and try again.",
  attest: "I have listed all items, quantities and values accurately, checked the prohibited-items guidance, and will open the parcel for inspection.", invalid: "Complete every item and tick the box to confirm the declaration.",
  save: "Save declaration", saving: "Saving…", failed: "Could not save. Please try again.", loadError: "Could not load the safety record. Retry before proceeding.", retry: "Retry", version: "Declaration version", missing: "A contents declaration is required before collection.", waitingDeclaration: "The sender must list the items and values and confirm the declaration before handover. Photos are optional.", frozen: "Once a request is accepted, the declaration is locked. To change the contents, cancel the match and update the parcel before arranging a new handover.",
  handover: "Inspect and confirm together", limits: "These records reduce risk; they do not certify legality or replace airline and customs checks. Refuse any item you cannot identify or inspect.", opened: "We opened the parcel and inspected every item together.", matches: "The contents and quantities match this declaration.", sealed: "We sealed the parcel together after inspection.", noConcerns: "I have no unresolved concerns about the contents or carriage restrictions.", confirm: "Confirm my inspection", confirmed: "Your inspection is recorded.", waitingOther: "Waiting for the other person to confirm this same declaration.", bothConfirmed: "Both people have confirmed. The traveller can now mark the parcel picked up.", sender: "Sender", traveller: "Traveller", waiting: "Not yet confirmed", record: "Confirmed", verify: "Traveller identity verification is required before pickup.", verifyLink: "Get verified", readyTerms: "Agree the terms first, then complete the inspection together at collection.",
  refuse: "Refuse parcel / Report concern", refusalNote: "Use this before taking the parcel. The match will be cancelled, reserved space released, and the parcel held for support review. There is no platform penalty for a safety refusal.", reason: "Reason", notes: "Additional details (optional)", confirmRefusal: "Confirm safety refusal", back: "Go back", refused: "This parcel was refused for a safety concern and is held for support review. No pickup should take place.",
  contents_mismatch: "Contents do not match the declaration", cannot_inspect: "The parcel cannot be opened or fully inspected", prohibited_or_restricted: "Suspected prohibited or restricted item", other_safety_concern: "Another safety concern",
};

const fr: typeof en = {
  inspectionAttest: "Je confirme que nous avons ouvert et inspecté le colis ensemble, que son contenu correspond à la déclaration et que nous l’avons scellé sans inquiétude de sécurité non résolue.",
  savedRequest: "Votre colis est enregistré. Réessayez la demande ou gérez-le dans votre tableau de bord.",
  upcoming: "Prochains voyageurs", upcomingNote: "Voyez qui voyage et à quelle date. Aucune date nécessaire pour consulter.", viewAll: "Voir tous les voyageurs", viewTrip: "Voir le voyage",
  later: "Voyageurs partant après la date choisie", laterNote: "Ces départs sont hors de la période choisie. Confirmez l'arrivée et la remise avant de demander.", seeLater: "Voir les départs suivants", anyDate: "Toutes les prochaines dates sur ce trajet.", noUpcoming: "Aucun voyage à venir. Publiez votre colis pour que les voyageurs vous trouvent.",
  title: "Déclaration du contenu", private: "La liste, les valeurs et les photos sont réservées à vous et aux voyageurs associés à ce colis. L'assistance peut les consulter si nécessaire.",
  item: "Description de l'article", quantity: "Quantité", value: "Valeur de cette ligne (USD)", addItem: "Ajouter un article", remove: "Retirer", total: "Valeur totale du contenu", valueNote: "La valeur des biens, distincte du prix payé au voyageur.",
  photos: "Photos du contenu ouvert (facultatif)", handoverPhotos: "Photos de la remise (facultatif)", photoNote: "Photos facultatives : jusqu’à 6 photos JPG, PNG ou WebP, 8 Mo maximum chacune. Ne photographiez pas de pièces d'identité ni de coordonnées.", addPhotos: "Ajouter des photos", uploading: "Envoi des photos…", photoError: "Utilisez des photos JPG, PNG ou WebP de moins de 8 Mo (6 maximum).", photoLoadError: "Photo indisponible. Actualisez et réessayez.",
  attest: "J'ai déclaré tous les articles, quantités et valeurs, consulté les objets interdits et j'ouvrirai le colis pour inspection.", invalid: "Complétez chaque article et cochez la case pour confirmer la déclaration.",
  save: "Enregistrer la déclaration", saving: "Enregistrement…", failed: "Enregistrement impossible. Réessayez.", loadError: "Impossible de charger le dossier. Réessayez avant de continuer.", retry: "Réessayer", version: "Version de la déclaration", missing: "Une déclaration du contenu est requise avant la collecte.", waitingDeclaration: "L'expéditeur doit déclarer les articles et leurs valeurs, puis confirmer la déclaration avant la remise. Les photos sont facultatives.", frozen: "Après acceptation, la déclaration est verrouillée. Pour changer le contenu, annulez la mise en relation et modifiez le colis avant une nouvelle remise.",
  handover: "Inspectez et confirmez ensemble", limits: "Ces preuves réduisent les risques sans certifier la légalité ni remplacer les contrôles des compagnies et douanes. Refusez tout article impossible à identifier ou inspecter.", opened: "Nous avons ouvert le colis et inspecté chaque article ensemble.", matches: "Le contenu et les quantités correspondent à cette déclaration.", sealed: "Nous avons scellé le colis ensemble après inspection.", noConcerns: "Je n'ai aucune inquiétude non résolue concernant le contenu ou les restrictions de transport.", confirm: "Confirmer mon inspection", confirmed: "Votre inspection est enregistrée.", waitingOther: "En attente de la confirmation de l'autre personne pour cette déclaration.", bothConfirmed: "Les deux personnes ont confirmé. Le voyageur peut marquer le colis comme récupéré.", sender: "Expéditeur", traveller: "Voyageur", waiting: "Pas encore confirmé", record: "Confirmé", verify: "L'identité du voyageur doit être vérifiée avant la collecte.", verifyLink: "Faire vérifier mon identité", readyTerms: "Convenez d'abord des conditions, puis inspectez le colis ensemble lors de la collecte.",
  refuse: "Refuser le colis / Signaler un problème", refusalNote: "À utiliser avant de prendre le colis. La mise en relation sera annulée, la place libérée et le colis bloqué pour examen. Aucun frais ni pénalité de plateforme pour un refus de sécurité.", reason: "Motif", notes: "Précisions (facultatif)", confirmRefusal: "Confirmer le refus de sécurité", back: "Retour", refused: "Ce colis a été refusé pour un problème de sécurité et attend un examen. Aucune collecte ne doit avoir lieu.",
  contents_mismatch: "Le contenu ne correspond pas à la déclaration", cannot_inspect: "Impossible d'ouvrir ou d'inspecter entièrement le colis", prohibited_or_restricted: "Objet potentiellement interdit ou réglementé", other_safety_concern: "Autre problème de sécurité",
};

const sw: typeof en = {
  inspectionAttest: "Nathibitisha kuwa tumefungua na kukagua kifurushi pamoja, yaliyomo yanafanana na tamko, na tumekifunga bila wasiwasi wowote wa usalama ambao haujatatuliwa.",
  savedRequest: "Kifurushi chako kimehifadhiwa. Jaribu ombi tena au kidhibiti kwenye dashibodi yako.",
  upcoming: "Wasafiri wa safari zijazo", upcomingNote: "Ona nani anasafiri na lini. Huhitaji kuchagua tarehe kwanza.", viewAll: "Ona wasafiri wote", viewTrip: "Ona safari",
  later: "Wasafiri wanaoondoka baada ya tarehe uliyochagua", laterNote: "Safari hizi ziko nje ya muda uliouchagua. Thibitisheni kuwasili na makabidhiano kabla ya kutuma ombi.", seeLater: "Ona safari za baadaye", anyDate: "Tarehe zote zijazo kwenye njia hii zinaonyeshwa.", noUpcoming: "Hakuna safari zijazo bado. Chapisha kifurushi chako ili wasafiri wakupate.",
  title: "Tamko la yaliyomo", private: "Orodha ya vitu, thamani na picha zinaonekana kwako na wasafiri waliounganishwa na kifurushi hiki pekee. Huduma kwa wateja inaweza kuzipitia ikihitajika.",
  item: "Maelezo ya kitu", quantity: "Idadi", value: "Thamani ya vitu kwenye mstari huu (USD)", addItem: "Ongeza kitu kingine", remove: "Ondoa", total: "Thamani ya yaliyomo", valueNote: "Thamani ya vitu, tofauti na ada unayomlipa msafiri.",
  photos: "Picha za yaliyomo kabla ya kufunga (hiari)", handoverPhotos: "Picha za makabidhiano (hiari)", photoNote: "Picha ni za hiari. Ongeza hadi picha 6 za JPG, PNG au WebP, hadi MB 8 kila moja. Usijumuishe vitambulisho au mawasiliano kwenye picha.", addPhotos: "Ongeza picha", uploading: "Inapakia picha…", photoError: "Tumia picha za JPG, PNG au WebP chini ya MB 8 (hadi picha 6).", photoLoadError: "Picha haipatikani. Onyesha ukurasa upya na ujaribu tena.",
  attest: "Nimeorodhesha vitu vyote, idadi na thamani kwa usahihi, nimesoma mwongozo wa vitu vilivyokatazwa, na nitafungua kifurushi kikaguliwe.", invalid: "Jaza kila kitu na uweke tiki kwenye kisanduku kuthibitisha tamko.",
  save: "Hifadhi tamko", saving: "Inahifadhi…", failed: "Haikuweza kuhifadhi. Jaribu tena.", loadError: "Rekodi haikuweza kupakiwa. Jaribu tena kabla ya kuendelea.", retry: "Jaribu tena", version: "Toleo la tamko", missing: "Tamko la yaliyomo linahitajika kabla ya kuchukua kifurushi.", waitingDeclaration: "Mtumaji lazima aorodheshe vitu na thamani zake na athibitishe tamko kabla ya makabidhiano. Picha ni za hiari.", frozen: "Ombi likikubaliwa, tamko linafungwa. Kubadili yaliyomo, ghairi makubaliano na usasishe kifurushi kabla ya kupanga makabidhiano mapya.",
  handover: "Kagueni na kuthibitisha pamoja", limits: "Rekodi hizi hupunguza hatari; hazithibitishi uhalali wala kuchukua nafasi ya ukaguzi wa ndege na forodha. Kataa kitu chochote usichoweza kutambua au kukagua.", opened: "Tumefungua kifurushi na kukagua kila kitu pamoja.", matches: "Vitu na idadi vinafanana na tamko hili.", sealed: "Tumefunga kifurushi pamoja baada ya ukaguzi.", noConcerns: "Sina wasiwasi ambao haujatatuliwa kuhusu yaliyomo au masharti ya usafirishaji.", confirm: "Thibitisha ukaguzi wangu", confirmed: "Ukaguzi wako umerekodiwa.", waitingOther: "Inasubiri mtu mwingine athibitishe tamko hili pia.", bothConfirmed: "Wote wawili wamethibitisha. Msafiri anaweza sasa kuashiria amechukua kifurushi.", sender: "Mtumaji", traveller: "Msafiri", waiting: "Bado hajathibitisha", record: "Amethibitisha", verify: "Utambulisho wa msafiri lazima uthibitishwe kabla ya kuchukua kifurushi.", verifyLink: "Thibitisha utambulisho", readyTerms: "Kubalianeni masharti kwanza, kisha kagueni kifurushi pamoja wakati wa kukichukua.",
  refuse: "Kataa kifurushi / Ripoti wasiwasi", refusalNote: "Tumia kabla ya kuchukua kifurushi. Makubaliano yataghairiwa, nafasi itarejeshwa, na kifurushi kitasimamishwa kipitiwe na huduma kwa wateja. Hakuna adhabu ya jukwaa kwa kukataa kwa sababu ya usalama.", reason: "Sababu", notes: "Maelezo zaidi (hiari)", confirmRefusal: "Thibitisha kukataa kwa usalama", back: "Rudi", refused: "Kifurushi hiki kimekataliwa kwa sababu ya usalama na kinasubiri ukaguzi. Kisichukuliwe.",
  contents_mismatch: "Yaliyomo hayafanani na tamko", cannot_inspect: "Kifurushi hakiwezi kufunguliwa au kukaguliwa kikamilifu", prohibited_or_restricted: "Kitu kinachoshukiwa kukatazwa au kuhitaji kibali", other_safety_concern: "Wasiwasi mwingine wa usalama",
};

export const safetyCopy = { en, fr, sw };
